Fix repeating group read tags lost
quickfixgo/quickfix pull request #462
Opened 2021-09-24 15:42 UTC by hyde-zhang

The ```RepeatingGroup``` tags are not created during the read process. Tag values are there but tags are not copied over / read. If `CopyInto` is used to copy from old `FieldMap` to new, existing tags from old one will be lost during the [fields setting process](https://github.com/quickfixgo/quickfix/blob/main/repeating_group.go#L116)

Can try to reproduce like this: 

```go
	symGroup := quoterequest.NewNoRelatedSymRepeatingGroup()
	sym := symGroup.Add()
	sym.SetSymbol("symbol")
	sym.SetOrderQty(decimal.NewFromFloat(1), 4)
	sym.SetQuoteRequestType(enum.QuoteRequestType_AUTOMATIC)
	
	fixmsg := quoterequest.New(field.NewQuoteReqID("testId"))
	fixmsg.SetNoRelatedSym(symGroup)

	msg := quoterequest.FromMessage(fixmsg.ToMessage())
	if syms, err := msg.GetNoRelatedSym(); err == nil {

		newSyms := quoterequest.NewNoRelatedSymRepeatingGroup()
		newSym := newSyms.Add()

		sym := syms.Get(0)
		sym.CopyInto(&newSym.FieldMap) // SUT

		newSym.SetCurrency("USD")
		msg.SetNoRelatedSym(newSyms)
		// log msg.ToMessage() will show only Currency (15) tag
		// 8=FIX.4.4 9=29 35=R 131=testId 146=1 15=USD 10=213 
		// Whereas it should be
		// 8=FIX.4.4 9=55 35=R 131=testId 146=1 55=symbol 303=2 38=1.0000 15=USD 10=224
	}
```

2022-06-29 02:33 UTC, totalys approved these changes

2022-06-29 02:34 UTC, totalys requested changes
resolve conflicts

2022-09-01 20:12 UTC, rtjoseph11 commented
@totalys we're hitting this bug in production with NSCC. What is your plan/timeline for merging this?

2022-09-02 04:08 UTC, totalys commented
I'm not allowed to merge. I'would like this to me merged asap as well! Please @ackleymi , @hyde-zhang, @reedom.

2022-09-24 09:40 UTC, sylr commented
Related: https://github.com/quickfixgo/quickfix/pull/509

2022-09-24 10:14 UTC, sylr approved these changes

2022-09-24 14:03 UTC, rtjoseph11 commented
@sylr do you know who can merge this?

2022-09-24 15:30 UTC, sylr commented
> @sylr do you know who can merge this?

@ackleymi I believe.

2022-09-28 20:00 UTC, rtjoseph11 commented
@ackleymi anything holding up merging this?

2023-01-26 21:33 UTC, rtjoseph11 commented
@ackleymi can you please respond here?

2023-01-29 03:22 UTC, merged